"use client";

import { useState } from "react";
import { MessageSquareText, Pencil, Search, Star, Trash2, X } from "lucide-react";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { Pagination } from "@/components/common/pagination";
import { Button } from "@/components/ui/button";

type ReviewStatus = "pending" | "approved" | "hidden";
type Review = { id: number; userId: number; locationId: number; rating: number; comment: string; status: ReviewStatus };
const initial: Review[] = [
  { id: 1, userId: 1, locationId: 1, rating: 5, comment: "Beautiful and worth visiting.", status: "approved" },
  { id: 2, userId: 2, locationId: 2, rating: 4, comment: "Clear map and good 360 preview.", status: "approved" },
  { id: 3, userId: 3, locationId: 3, rating: 5, comment: "The audio narration was helpful.", status: "pending" },
  { id: 4, userId: 4, locationId: 2, rating: 2, comment: "Needs moderation.", status: "hidden" },
  { id: 5, userId: 5, locationId: 4, rating: 4, comment: "Nice route.", status: "pending" },
  { id: 6, userId: 6, locationId: 5, rating: 5, comment: "Great staff support.", status: "approved" }
];
export default function StaffReviewsPage() {
  const [items, setItems] = useState(initial); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Review | null>(null); const [deleting, setDeleting] = useState<Review | null>(null); const pageSize = 5;
  const visible = items.filter((item) => `${item.userId} ${item.locationId} ${item.comment} ${item.status}`.toLowerCase().includes(query.toLowerCase())); const pageCount = Math.max(1, Math.ceil(visible.length / pageSize)); const currentPage = Math.min(page, pageCount); const rows = visible.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  function save(payload: Review) { setItems((current) => current.map((item) => item.id === payload.id ? payload : item)); setEditing(null); }
  function remove() { if (!deleting) return; setItems((current) => current.filter((item) => item.id !== deleting.id)); setDeleting(null); }
  return <><Panel title="Staff Reviews" desc="Moderate location reviews." query={query} setQuery={(v) => { setQuery(v); setPage(1); }} heads={["Review", "User ID", "Location ID", "Rating", "Comment", "Status", "Actions"]}>{rows.map((item) => <tr key={item.id} className="border-t border-slate-100"><td className="p-3 font-bold"><MessageSquareText className="mr-2 inline size-4 text-brand-600" />#{item.id}</td><td className="p-3">{item.userId}</td><td className="p-3">{item.locationId}</td><td className="p-3"><Star className="mr-1 inline size-4 fill-amber-400 text-amber-400" />{item.rating}</td><td className="max-w-64 truncate p-3 text-slate-600">{item.comment}</td><td className="p-3"><Status value={item.status} /></td><td className="p-3"><span className="flex gap-2"><Button variant="outline" className="h-9 px-3" onClick={() => setEditing(item)}><Pencil size={15} /> Edit</Button><button type="button" onClick={() => setDeleting(item)} className="grid size-9 place-items-center rounded-lg border border-rose-200 text-rose-600 hover:bg-rose-50"><Trash2 size={15} /></button></span></td></tr>)}</Panel><Pagination page={currentPage} pageCount={pageCount} totalItems={visible.length} pageSize={pageSize} itemLabel="reviews" onPageChange={setPage} />{editing ? <ReviewModal item={editing} onClose={() => setEditing(null)} onSave={save} /> : null}{deleting ? <ConfirmDialog title="Delete Review" message={`Delete review #${deleting.id}?`} onCancel={() => setDeleting(null)} onConfirm={remove} /> : null}</>;
}
function ReviewModal({ item, onClose, onSave }: { item: Review; onClose: () => void; onSave: (item: Review) => void }) { const [form, setForm] = useState(item); return <Modal title="Edit Review" onClose={onClose} onSubmit={() => onSave(form)}><div className="grid gap-4"><Field label="Rating"><select value={form.rating} onChange={(e) => setForm({ ...form, rating: Number(e.target.value) })} className="input"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></Field><Field label="Comment"><textarea value={form.comment} onChange={(e) => setForm({ ...form, comment: e.target.value })} className="input min-h-24 py-3" /></Field><Field label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ReviewStatus })} className="input"><option>pending</option><option>approved</option><option>hidden</option></select></Field></div></Modal>; }
function Panel({ title, desc, query, setQuery, heads, children }: { title: string; desc: string; query: string; setQuery: (v: string) => void; heads: string[]; children: React.ReactNode }) { return <div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">{title}</h1><p className="mt-1 text-sm text-slate-500">{desc}</p><div className="relative mt-6 max-w-md"><Search className="absolute left-3 top-3 size-5 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-11 w-full rounded-lg border border-slate-200 pl-10 pr-4 text-sm outline-none focus:border-brand-600" placeholder="Search..." /></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[860px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{heads.map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div></div>; }
function Modal({ title, children, onClose, onSubmit }: { title: string; children: React.ReactNode; onClose: () => void; onSubmit: () => void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><form className="w-full max-w-xl rounded-lg border border-slate-200 bg-white p-6 shadow-soft" onSubmit={(e) => { e.preventDefault(); onSubmit(); }}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button type="button" onClick={onClose} className="grid size-9 place-items-center rounded-full hover:bg-slate-100"><X size={18} /></button></div><div className="mt-6">{children}</div><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save</Button></div></form></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold [&_.input]:mt-2 [&_.input]:h-11 [&_.input]:w-full [&_.input]:rounded-lg [&_.input]:border [&_.input]:border-slate-200 [&_.input]:px-3">{label}{children}</label>; }
function Status({ value }: { value: string }) { const style = value === "approved" ? "bg-emerald-50 text-emerald-700" : value === "hidden" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-3 py-1 text-xs font-bold ${style}`}>{value}</span>; }
