"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Eye, ImagePlus, Loader2, Plus, RefreshCw, Trash2, Upload, X } from "lucide-react";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { useToast } from "@/components/common/toast";
import { Button } from "@/components/ui/button";
import { resolveBackendAssetUrl } from "@/lib/avatar";
import { getTravelStoryId, getTravelStoryMedia, travelStoryService, type TravelStory, type TravelStoryViewer } from "@/services/travel-story.service";
import { useAuthStore } from "@/store/use-auth-store";

export default function MyTravelStoriesPage() {
  const user = useAuthStore((state) => state.user);
  const role = String(user?.role ?? "").toLowerCase();
  const [items, setItems] = useState<TravelStory[]>([]); const [status, setStatus] = useState<"active" | "expired">("active"); const [loading, setLoading] = useState(true); const [creating, setCreating] = useState(false); const [deleting, setDeleting] = useState<TravelStory | null>(null); const [viewing, setViewing] = useState<TravelStory | null>(null); const [viewers, setViewers] = useState<TravelStoryViewer[]>([]); const [error, setError] = useState(""); const showToast = useToast();
  const load = useCallback(async () => { if (role !== "customer") { setLoading(false); return; } setLoading(true); setError(""); try { setItems(await travelStoryService.mine({ page: 1, limit: 100, status })); } catch { setError("Cannot load your travel stories."); } finally { setLoading(false); } }, [role, status]);
  useEffect(() => { if (role) void load(); }, [load, role]);
  async function remove() { if (!deleting) return; try { await travelStoryService.remove(getTravelStoryId(deleting)); setDeleting(null); await load(); showToast({ variant: "success", title: "Story deleted" }); } catch { setError("Cannot delete this story."); } }
  async function openViewers(story: TravelStory) { setViewing(story); try { setViewers(await travelStoryService.viewers(getTravelStoryId(story), { page: 1, limit: 100 })); } catch { setViewers([]); } }
  if (role && role !== "customer") return <div className="rounded-lg border border-amber-200 bg-amber-50 p-8 text-center shadow-sm"><ImagePlus className="mx-auto size-10 text-amber-600" /><h1 className="mt-4 text-2xl font-bold text-amber-900">Customer-only feature</h1><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-amber-800">My Travel Stories is available only to customer accounts. Admin and staff can view active customer stories from the Travel Feed, but cannot create, delete, or manage personal stories.</p><Button href="/travel-feed" variant="outline" className="mt-6">Open Travel Feed</Button></div>;
  return <><div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">My Travel Stories</h1><p className="mt-1 text-sm text-slate-500">Manage your 24-hour image and video stories.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw size={16} className={loading ? "animate-spin" : ""} />Refresh</Button><Button onClick={() => setCreating(true)}><Plus size={16} />Add Story</Button></div></div>{error ? <p className="mt-5 rounded-lg bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p> : null}<div className="mt-6 flex gap-2">{(["active", "expired"] as const).map((value) => <button key={value} onClick={() => setStatus(value)} className={`rounded-full px-4 py-2 text-sm font-bold capitalize ${status === value ? "bg-brand-600 text-white" : "bg-slate-100 text-slate-600"}`}>{value}</button>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{loading ? Array.from({ length: 6 }, (_, index) => <div key={index} className="aspect-[3/4] animate-pulse rounded-xl bg-slate-100" />) : items.length ? items.map((story) => <article key={getTravelStoryId(story)} className="group relative aspect-[3/4] overflow-hidden rounded-xl bg-slate-950">{story.media_type === "video" ? <video src={resolveBackendAssetUrl(getTravelStoryMedia(story))} className="size-full object-cover" /> : <img src={resolveBackendAssetUrl(getTravelStoryMedia(story))} alt={story.caption ?? "Story"} className="size-full object-cover" />}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/90 to-transparent p-4 text-white">{story.caption ? <p className="line-clamp-3 text-sm">{story.caption}</p> : null}<div className="mt-3 flex items-center justify-between"><button onClick={() => void openViewers(story)} className="inline-flex items-center gap-1 text-xs font-bold"><Eye size={14} />{story.viewer_count ?? 0} viewers</button><button onClick={() => setDeleting(story)} className="grid size-9 place-items-center rounded-full bg-white/15 text-rose-200"><Trash2 size={16} /></button></div></div></article>) : <div className="col-span-full rounded-lg border border-dashed border-slate-200 p-12 text-center text-slate-500"><ImagePlus className="mx-auto mb-3 size-8" />No {status} stories.</div>}</div></div>{creating ? <CreateStory onClose={() => setCreating(false)} onCreated={() => { setCreating(false); void load(); }} /> : null}{viewing ? <ViewersModal story={viewing} viewers={viewers} onClose={() => setViewing(null)} /> : null}{deleting ? <ConfirmDialog title="Delete story?" message="This story will be removed from the feed." onCancel={() => setDeleting(null)} onConfirm={() => void remove()} /> : null}</>;
}

function CreateStory({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [file, setFile] = useState<File | null>(null); const [caption, setCaption] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const preview = useMemo(() => file ? URL.createObjectURL(file) : "", [file]); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]); async function submit() { if (!file) { setError("Choose an image or video."); return; } if (file.size > 50 * 1024 * 1024) { setError("Maximum file size is 50 MB."); return; } setSaving(true); try { await travelStoryService.create(file, caption); onCreated(); } catch { setError("Cannot publish this story."); } finally { setSaving(false); } } return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-6"><div className="flex justify-between"><h2 className="text-xl font-bold">Add Travel Story</h2><button onClick={onClose}><X /></button></div><label className="mt-5 grid min-h-64 cursor-pointer place-items-center overflow-hidden rounded-xl border border-dashed border-slate-300 bg-slate-50">{preview ? file?.type.startsWith("video/") ? <video src={preview} controls className="max-h-80 w-full" /> : <img src={preview} alt="Preview" className="max-h-80 w-full object-contain" /> : <span className="text-center text-sm text-slate-500"><Upload className="mx-auto mb-2" />Choose image or video</span>}<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm,video/quicktime" className="hidden" onChange={(event) => { setError(""); setFile(event.target.files?.[0] ?? null); }} /></label><textarea value={caption} onChange={(event) => setCaption(event.target.value.slice(0, 1000))} className="mt-4 min-h-24 w-full rounded-lg border border-slate-200 p-3" placeholder="Caption..." />{error ? <p className="mt-2 text-sm font-semibold text-rose-600">{error}</p> : null}<Button className="mt-5 w-full" onClick={() => void submit()} disabled={saving}>{saving ? <Loader2 className="size-4 animate-spin" /> : null}Publish Story</Button></div></div>; }

function ViewersModal({ story, viewers, onClose }: { story: TravelStory; viewers: TravelStoryViewer[]; onClose: () => void }) { return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/50 p-4"><div className="w-full max-w-md rounded-xl bg-white p-6"><div className="flex justify-between"><div><h2 className="text-xl font-bold">Story Viewers</h2><p className="mt-1 text-sm text-slate-500">{story.viewer_count ?? viewers.length} total views</p></div><button onClick={onClose}><X /></button></div><div className="mt-5 max-h-80 space-y-2 overflow-auto">{viewers.length ? viewers.map((viewer, index) => <div key={viewer.user_id ?? viewer.id ?? index} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3"><span className="grid size-10 place-items-center rounded-full bg-brand-50 font-bold text-brand-700">{viewer.avatar_url ? <img src={resolveBackendAssetUrl(viewer.avatar_url)} alt="" className="size-full rounded-full object-cover" /> : (viewer.name ?? "T").charAt(0)}</span><div><p className="font-semibold">{viewer.name ?? `Customer #${viewer.user_id ?? viewer.id}`}</p>{viewer.viewed_at ? <p className="text-xs text-slate-400">{new Date(viewer.viewed_at).toLocaleString("vi-VN")}</p> : null}</div></div>) : <p className="py-8 text-center text-sm text-slate-500">No viewers yet.</p>}</div></div></div>; }
