"use client";

import { useState } from "react";
import { CreditCard, Pencil, RotateCcw, Search, X } from "lucide-react";
import { Pagination } from "@/components/common/pagination";
import { Button } from "@/components/ui/button";
import { currency } from "@/lib/utils";

type PaymentStatus = "pending" | "paid" | "failed" | "expired" | "refunded";
type Payment = { id: number; bookingId: number; amount: number; status: PaymentStatus; transactionCode: string };
const initial: Payment[] = [
  { id: 1, bookingId: 2048, amount: 700000, status: "paid", transactionCode: "TXN-827391" },
  { id: 2, bookingId: 2052, amount: 520000, status: "pending", transactionCode: "TXN-827402" },
  { id: 3, bookingId: 2054, amount: 1200000, status: "paid", transactionCode: "TXN-827455" },
  { id: 4, bookingId: 2055, amount: 450000, status: "failed", transactionCode: "TXN-827461" },
  { id: 5, bookingId: 1988, amount: 900000, status: "refunded", transactionCode: "TXN-826910" },
  { id: 6, bookingId: 2060, amount: 350000, status: "expired", transactionCode: "TXN-828000" }
];
export default function StaffPaymentsPage() {
  const [items, setItems] = useState(initial); const [query, setQuery] = useState(""); const [page, setPage] = useState(1); const [editing, setEditing] = useState<Payment | null>(null); const [refunding, setRefunding] = useState<Payment | null>(null); const pageSize = 5;
  const visible = items.filter((item) => `${item.id} ${item.bookingId} ${item.status} ${item.transactionCode}`.toLowerCase().includes(query.toLowerCase())); const pageCount = Math.max(1, Math.ceil(visible.length / pageSize)); const currentPage = Math.min(page, pageCount); const rows = visible.slice((currentPage - 1) * pageSize, currentPage * pageSize);
  function save(payload: Payment) { setItems((current) => current.map((item) => item.id === payload.id ? payload : item)); setEditing(null); }
  function refund(payload: Payment) { setItems((current) => current.map((item) => item.id === payload.id ? { ...payload, status: "refunded" } : item)); setRefunding(null); }
  return <><div className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">Staff Payments</h1><p className="mt-1 text-sm text-slate-500">Update payment status and process refunds.</p><div className="relative mt-6 max-w-md"><Search className="absolute left-3 top-3 size-5 text-slate-400" /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1); }} className="h-11 w-full rounded-lg border border-slate-200 pl-10 pr-4 text-sm outline-none focus:border-brand-600" placeholder="Search payments..." /></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{["Payment", "Booking", "Amount", "Status", "Transaction", "Actions"].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((item) => <tr key={item.id} className="border-t border-slate-100"><td className="p-3 font-bold"><CreditCard className="mr-2 inline size-4 text-brand-600" />#{item.id}</td><td className="p-3">BK-{item.bookingId}</td><td className="p-3">{currency(item.amount)}</td><td className="p-3"><Status value={item.status} /></td><td className="p-3 text-slate-600">{item.transactionCode}</td><td className="p-3"><span className="flex gap-2"><Button variant="outline" className="h-9 px-3" onClick={() => setEditing(item)}><Pencil size={15} /> Status</Button><Button variant="outline" className="h-9 px-3" onClick={() => setRefunding(item)}><RotateCcw size={15} /> Refund</Button></span></td></tr>)}</tbody></table></div><Pagination page={currentPage} pageCount={pageCount} totalItems={visible.length} pageSize={pageSize} itemLabel="payments" onPageChange={setPage} /></div>{editing ? <PaymentModal title="Update Payment Status" item={editing} onClose={() => setEditing(null)} onSave={save} /> : null}{refunding ? <PaymentModal title="Refund Payment" item={refunding} onClose={() => setRefunding(null)} onSave={refund} /> : null}</>;
}
function PaymentModal({ title, item, onClose, onSave }: { title: string; item: Payment; onClose: () => void; onSave: (item: Payment) => void }) { const [form, setForm] = useState(item); return <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4"><form className="w-full max-w-md rounded-lg border border-slate-200 bg-white p-6 shadow-soft" onSubmit={(e) => { e.preventDefault(); onSave(form); }}><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{title}</h2><button type="button" onClick={onClose} className="grid size-9 place-items-center rounded-full hover:bg-slate-100"><X size={18} /></button></div><div className="mt-6 grid gap-4"><Field label="Amount"><input type="number" value={form.amount} onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })} className="input" /></Field><Field label="Transaction Code"><input value={form.transactionCode} onChange={(e) => setForm({ ...form, transactionCode: e.target.value })} className="input" /></Field><Field label="Status"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as PaymentStatus })} className="input"><option>pending</option><option>paid</option><option>failed</option><option>expired</option><option>refunded</option></select></Field></div><div className="mt-6 flex justify-end gap-3"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save</Button></div></form></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold [&_.input]:mt-2 [&_.input]:h-11 [&_.input]:w-full [&_.input]:rounded-lg [&_.input]:border [&_.input]:border-slate-200 [&_.input]:px-3">{label}{children}</label>; }
function Status({ value }: { value: string }) { const style = value === "paid" ? "bg-emerald-50 text-emerald-700" : value === "failed" ? "bg-rose-50 text-rose-700" : value === "refunded" ? "bg-blue-50 text-blue-700" : "bg-amber-50 text-amber-700"; return <span className={`rounded-full px-3 py-1 text-xs font-bold ${style}`}>{value}</span>; }
